### ISSUE TITLE
Description too short

### ISSUE THREAD

**Issue by ugurdogrusoz** [boranyldrm/CS319-2c#1]
You need to expand your description. Also mention (with references) any similar software publicly available and discuss how yours will differ from them.

**Comment by boranyldrm** [comment]
Following Saturday's meeting, the description will be detailed.

**Comment by ugurdogrusoz** [comment]
Isn't that too late! The next deadline (requirements) is approaching fast and you aren't done with this one yet.

**Comment by BerkeSoysal** [comment]
Read me updated.
