### ISSUE TITLE
DataManager.java operations

### ISSUE THREAD

**Issue by boranyldrm** [boranyldrm/CS319-2c#6]
Data manager should save the data to a file and read the file when the program starts.
If you save it in an array, every time data will disappear.

**Comment by BerkeSoysal** [comment]
Also, I think we don't need to store the images, in data Manager, we can simply just include them in the package and retrieve from there when we need it.

**Comment by boranyldrm** [comment]
@BerkeSoysal I did not pay attention to the images, you are right. The DataManager should be responsible for just saving settings, scores, levels etc.
